name: Checkmarx SAST Scan

on:
  workflow_call:
    inputs:
      project_name:
        required: false
        type: string
      branch:
        required: false
        type: string

jobs:
  checkmarx-sast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Run Checkmarx One SAST Scan
        uses: Checkmarx/ast-github-action@v2
        with:
          base_uri: ${{ secrets.CX_BASE_URI }}
          cx_tenant: ${{ secrets.CX_TENANT }}
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}

          project_name: ${{ inputs.project_name || github.repository }}
          branch: ${{ inputs.branch || github.ref_name }}

          scan_params: >
            --scan-types sast
            --sast-preset-name "Checkmarx Default"

          results_params: >
            --report-format sarif
            --output-path cx_result.sarif

      - name: Upload SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: cx_result.sarif
